== League Overview
=== Committees
The Small Size League (SSL), like every other league of the RoboCup, is run by close cooperation of three different committees (<<Executive Committee, executive committee>>, <<Technical Committee, technical committee>> and <<Organizing Committee, organizing committee>>), all with a different set of responsibilities. 
In the case the Entry Level (SSL-EL) category, the committees are shared between the EL and the so-called regular categories of the SSL, which are the two standard divisions: div-A and div-B. For more information on these, see (https://ssl.robocup.org/rules/).

Additionally, the members of the <<Local Organizing Committee, local organizing committee>> organize the RoboCup event for all leagues.

==== Executive Committee
Executive committee members are responsible for the long term goals of the Small Size League and thus have also contact to other leagues as well as to the RoboCup federation. The executive committee presents the Small Size League and its achievements to the RoboCup federation every year and gets feedback to organize the league. Executive committee members are elected by the board of trustees of the RoboCup federation. They serve 3-year terms.

==== Technical Committee
The technical committee of the Small Size League is responsible for the technical aspects of the RoboCup, such as maintaining the rules and the shared software. All members are elected by the team leaders of the teams which have participated in the previous competition.

==== Organizing Committee
The organizing committee of the Small Size League is responsible for preparing and organizing the competition. This mainly includes making the schedule, performing the qualification process, and running the competition. The committee members are selected by the <<Executive Committee, executive committee>> of the league and the RoboCup trustees.

==== Local Organizing Committee
The local organizing committee is responsible for planning and executing the event itself in accordance with the needs of the different leagues. This includes setting up the team areas (fields, network, tables, whiteboard, screens, etc.), creating a schedule for the event and implementing a safety and security concept.